config/routes.rb
Rails.application.routes.draw do
  root 'homes#index'
  devise_for :users
  resources :users, only: [:show, :index, :edit, :update]
  resources :interest_tags, only: [:index]
  resources :skill_tags, only: [:index]
  get "recommended_projects" => "projects#recommended_projects",
    as: "recommended_projects"
  resources :projects
end

app/models/project.rb
class Project < ActiveRecord::Base
  belongs_to :user
  acts_as_taggable_on :skills
  acts_as_taggable_on :interests

  validate :at_least_2_skills
  validate :at_least_2_interests
  validates :name,
    presence: true,
    length: { minimum: 3, maximum: 40 },
    uniqueness: { scope: :user,
      message: "You already have a project by the same name" }

  validates :proposal,
    presence: true,
    length: { minimum: 50 },
    uniqueness: { scope: :user,
      message: "You already have a project with the same proposal" }

  def at_least_2_skills
    # if we return false in a callback the record will not be saved
    if skill_list.count >= 2
      true
    else
      errors.messages[:skill_error] = ["not enough skills"] # change error message appropriately
      false
    end
  end

  def at_least_2_interests
    # if we return false in a callback the record will not be saved
    if interest_list.count >= 2
      true
    else
      errors.messages[:interest_error] = ["not enough interests"] # change error message appropriately
      false
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :projects
  acts_as_taggable_on :skills
  acts_as_taggable_on :interests
  acts_as_tagger
  mount_uploader :profile_pic, ProfilePicUploader

  validate :at_least_2_skills
  validate :at_least_2_interests

  validates :username,
    presence: true,
    length: { minimum: 3, maximum: 15},
    uniqueness: true

  validates :first_name,
    presence: true,
    length: { maximum: 25 }

  validates :last_name,
    presence: true,
    length: { maximum: 25 }

  validates :about_me,
    presence: true,
    length: { minimum: 20 }

  validates :email,
    presence: true

  # make test for phone, zip, and profile pic
  def at_least_2_skills
    if skill_list.count >= 2
      true
    else
      errors.messages[:skill_error] = ["not enough skills"]
      false
    end
  end

  def at_least_2_interests
    # if we return false in a callback the record will not be saved
    if interest_list.count >= 2
      true
    else
      errors.messages[:interest_error] = ["not enough interests"] # change error message appropriately
      false
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resources)
    user_path(resource) || root_path
  end

  def after_sign_up_path_for(resources)
    user_path(resource) || root_path
  end

  def after_update_path_for(resource)
    user_path(resource)
  end

  include RecommendationsHelper

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:account_update) << [
      :username, :pone, :first_name, :last_name,
      :zip_code, :profile_pic, :remote_profile_pic_url, :about_me, :skill_list, :interest_list
      ]
    devise_parameter_sanitizer.for(:sign_up) << [
      :username, :pone, :first_name, :last_name,
      :zip_code, :profile_pic, :remote_profile_pic_url, :about_me, :skill_list, :interest_list
      ]
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
  end
end

app/controllers/interest_tags_controller.rb
class InterestTagsController < ApplicationController
  def index
    project_interest_tags = Project.tag_counts_on(:interests).where(
      "name like ?", "%#{params[:q]}%")
    user_interest_tags = User.tag_counts_on(:interests).where(
      "name like ?", "%#{params[:q]}%")

    all_interest_tags = project_interest_tags + user_interest_tags
    all_interest_tags.uniq!
    respond_to do |format|
      format.json { render json: all_interest_tags }
    end
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :authenticate_user!, except: [:all_skills, :all_interests]

  def new
    @project = Project.new
  end

  def create
    @project = current_user.projects.new(project_params)
    if @project.save
      flash[:success] = "Project created successfully!"
      redirect_to user_path(current_user)
    else
      flash[:error] = "Project creation failed"
      render :new
    end
  end

  def edit
    @project = current_user.projects.find(params[:id])
  end

  def update
    @project = Project.update(params[:id], project_params)
    if @project.save
      flash[:success] = "Project updated successfully"
      redirect_to(@project)
    else
      flash[:error] = "Update failed"
      render :new
    end
  end

  def show
    @project = Project.find(params[:id])
    @top_5_recommended_users = fetch_recommendations(
      @project, User)[0..4].to_h.keys
    @skills = @project.skills
    @interests = @project.interests
  end

  def index
    @projects = Project.all
  end

  def recommended_projects
    @recommended_projects = fetch_recommendations(
      current_user, Project).to_h.keys
  end

  def destroy
    @project = current_user.projects.find(params[:id])
    @project.destroy
    flash[:success] = "Project deleted successfully"
    redirect_to user_path(current_user)
  end

  private

  def project_params
    params.require(:project).permit(:name, :proposal, :skill_list, :interest_list)
  end
end

app/controllers/skill_tags_controller.rb
class SkillTagsController < ApplicationController
  def index
    project_skill_tags = Project.tag_counts_on(:skills).where(
      "name like ?", "%#{params[:q]}%")
    user_skill_tags = User.tag_counts_on(:skills).where(
      "name like ?", "%#{params[:q]}%")

    all_skill_tags = project_skill_tags + user_skill_tags
    all_skill_tags.uniq!

    respond_to do |format|
      format.json { render json: all_skill_tags }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def show
    @user = User.find(params[:id])
    @top_5_recommended_projects = fetch_recommendations(
      @user, Project)[0..4].to_h.keys
    @projects = @user.projects
    @skills = @user.skills
    @interests = @user.interests
  end

  def index
    @users = User.all
  end
end

app/helpers/recommendations_helper.rb
module RecommendationsHelper
  def fetch_recommendations(rec_for, rec_type)
    skills_interests_to_match = rec_for.skill_list + rec_for.interest_list
    recommendations = rec_type.tagged_with(
      [skills_interests_to_match], any: true)
    scored_recommendations = Hash.new

    recommendations.each do |rec|
      if recommendation_valid?(rec_for, rec)
        score = 0
        skill_intersection = rec.skill_list & rec_for.skill_list
        interest_intersection = rec.interest_list & rec_for.interest_list

        if skill_intersection.any? && interest_intersection.any?
          score += 3
          score = score + skill_intersection.count + interest_intersection.count
          scored_recommendations[rec] = score
        else
          score = skill_intersection.count + interest_intersection.count
          scored_recommendations[rec] = score
        end
      end
    end

    scored_recommendations = scored_recommendations.sort_by do |_rec, score|
      score
    end
    scored_recommendations.reverse
  end

  def recommendation_valid?(rec_for, rec)
    if rec_for != rec && rec_for.class != rec.class
      if rec_for.class == User
        return false if rec_for.projects.include?(rec)
      elsif rec_for.class == Project
        return false if rec_for.user == rec
      end
      return true
    else
      false
    end
  end

  def matches(object_1, object_2)
    matches = Array.new
    (object_1.skill_list & object_2.skill_list).each do |match|
      matches << { "skill" => match }
    end
    (object_1.interest_list & object_2.interest_list).each do |match|
      matches << { "interest" => match }
    end
    matches
  end
end

app/views/homes/index.html.erb
<body class="landing-page-body">
  <div class="row">
    <div class="small-12 columns splash-header">
      <h1>ENDEAVOR</h1>
      <h3>mobilize your skills and interests</h3>
      <h3>to collaborate on the projects you love</h3>
    </div>
  </div>


  <div class="row">
    <div class="small-12 columns splash-actions">
      <%- if current_user -%>
        <%= link_to 'Sign Out', destroy_user_session_path, method: :delete, class: "button large round" %>
        <%= link_to "My Profile",user_path(current_user), class: "button large round" %>
      <%- else -%>
        <%= link_to 'Sign Up', new_user_registration_path, class: "button large round" %>
        <%= link_to 'Sign In', new_user_session_path, class: "button large round" %>
      <%- end -%>
    </div>
  </div>
</body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Endeavor</title>
  <%= stylesheet_link_tag 'application', 'token-input', media: 'all' %>
  <%= csrf_meta_tags %>
  <link href='http://fonts.googleapis.com/css?family=Cabin|Gudea|Raleway' rel='stylesheet' type='text/css'>
</head>
<body>

  <%- flash.each do |key, value| -%>
    <div class="flash flash-<%= key %>">
      <%= value %>
    </div>
  <%- end -%>
      <%= yield %>

  <%= javascript_include_tag 'application' %>
  <%= yield :extra_footer %>

</body>
</html>

app/views/projects/edit.html.erb
<nav class="top-bar">
  <ul class="title-area">
    <li class="name">
      <h1><a href="/" id="nav-bar-name">Endeavor</a></h1>
    </li>
  </ul>

  <section class="top-bar-section">
    <ul class="right">
      <%- if current_user -%>
        <li><%= link_to("Recommended Projects", recommended_projects_path) %></li>
        <li><%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></li>
        <li><%= link_to "My Profile",user_path(current_user) %></li>
      <%- else -%>
        <li><%= link_to 'Sign Up', new_user_registration_path %></li>
        <li><%= link_to 'Sign In', new_user_session_path %></li>
      <%- end -%>
    </ul>
  </section>
</nav>

<div class="row">
  <div class="small-10 small-centered columns">
    <h1>Edit Project</h1>

    <% if @project.errors.any? %>
      <ul>
        <% @project.errors.full_messages.each do |er| %>
          <li> <%= er %> </li>
        <% end %>
      </ul>
    <% end %>

    <%= form_for @project do |f| %>
      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :proposal %>
      <%= f.text_field :proposal %>

      <%= f.label :skill_list, "Useful skills for this project" %>
      <%= f.text_field :skill_list, placeholder: "comma seperated", "data-pre" => @project.skills.map(&:attributes).to_json %>

      <%= f.label :interest_list, "Interests relevant to this project" %>
      <%= f.text_field :interest_list, placeholder: "comma seperated", "data-pre" => @project.interests.map(&:attributes).to_json %>

      <%= f.submit "Update Project", class: "button tiny success" %>
    <% end %>

    <%= link_to("back to project", project_path(@project)) %>
  </div>
</div>

app/views/projects/index.html.erb
<nav class="top-bar">
  <ul class="title-area">
    <li class="name">
      <h1><a href="/">Endeavor</a></h1>
    </li>
  </ul>

  <section class="top-bar-section">
    <ul class="right">
      <%- if current_user -%>
        <li><%= link_to("Recommended Projects", recommended_projects_path) %></li>
        <li><%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></li>
        <li><%= link_to "My Profile",user_path(current_user) %></li>
      <%- else -%>
        <li><%= link_to 'Sign Up', new_user_registration_path %></li>
        <li><%= link_to 'Sign In', new_user_session_path %></li>
      <%- end -%>
    </ul>
  </section>
</nav>

<body class="projects-page">
  <div class="row">
    <div class="small-12 columns">
      <h1>All Projects</h1>
      <% if @projects.empty? %>
        <h3>There are no projects at this time. Check again soon!</h3>
      <% else %>
        <ul>
          <% @projects.each do |project| %>
            <li><%= link_to(project.name, project_path(project)) %></li>
          <% end %>
        </ul>
      <% end %>
    </div>
  </div>
</body>

app/views/projects/new.html.erb
<nav class="top-bar">
  <ul class="title-area">
    <li class="name">
      <h1><a href="/" id="nav-bar-name">Endeavor</a></h1>
    </li>
  </ul>

  <section class="top-bar-section">
    <ul class="right">
      <%- if current_user -%>
        <li><%= link_to("Recommended Projects", recommended_projects_path) %></li>
        <li><%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></li>
        <li><%= link_to "My Profile",user_path(current_user) %></li>
      <%- else -%>
        <li><%= link_to 'Sign Up', new_user_registration_path %></li>
        <li><%= link_to 'Sign In', new_user_session_path %></li>
      <%- end -%>
    </ul>
  </section>
</nav>

<div class="row">
  <div class="small-10 small-centered columns">
    <h1>New Project</h1>
    <% if @project.errors.any? %>
      <ul>
        <% @project.errors.full_messages.each do |er| %>
          <li> <%= er %> </li>
        <% end %>
      </ul>
    <% end %>

    <%= form_for @project do |f| %>
      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :proposal %>
      <%= f.text_field :proposal %>

      <%= f.label :skill_list, "Useful skills for this project" %>
      <%= f.text_field :skill_list, placeholder: "comma seperated" %>

      <%= f.label :interest_list, "Interests relevant to this project" %>
      <%= f.text_field :interest_list, placeholder: "comma seperated" %>

      <%= f.submit "Create Project", class: "button tiny success" %>
    <% end %>
  </div>
</div>

app/views/projects/recommended_projects.html.erb
<nav class="top-bar">
  <ul class="title-area">
    <li class="name">
      <h1><a href="/" id="nav-bar-name">Endeavor</a></h1>
    </li>
  </ul>

  <section class="top-bar-section">
    <ul class="right">
      <%- if current_user -%>
        <li><%= link_to("Recommended Projects", recommended_projects_path) %></li>
        <li><%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></li>
        <li><%= link_to "My Profile",user_path(current_user) %></li>
      <%- else -%>
        <li><%= link_to 'Sign Up', new_user_registration_path %></li>
        <li><%= link_to 'Sign In', new_user_session_path %></li>
      <%- end -%>
    </ul>
  </section>
</nav>

<body class="recommended-projects-page">
  <div class="row">
    <h1>Recommended Projects</h1>
  <% if @recommended_projects.empty? %>
    <h3>You have no recommended projects at this time. Check again soon!</h3>
  <% else %>
    <ul id="recommended-project-list">
      <% @recommended_projects.each do |project| %>
        <div class="row recommended-project-row">
          <div class="small-3 columns" id="project-name-column">
            <%= link_to(project.name, project_path(project)) %>
            <p><%= project.proposal %></p>
          </div>

          <div class="small-3 columns project-skill-column">
            <% if project.skill_list.empty? %>
              <h6>This project hasn't been tagged with any skills yet</h6>
            <% else %>
              <h6>Skills</h6>
              <ul>
                <% project.skill_list.each do |skill| %>
                  <% if current_user.skill_list.include?(skill) %>
                    <li class="match"><%= skill %></li>
                  <% else %>
                    <li><%= skill %></li>
                  <% end %>
                <% end %>
              </ul>
            <% end %>
          </div>

          <div class="small-3 columns project-interest-column">
            <% if project.interest_list.empty? %>
              <h6>This project hasn't been tagged with any interests yet</h6>
            <% else %>
              <h6>Interests</h6>
              <ul>
                <% project.interest_list.each do |interest| %>
                  <% if current_user.interest_list.include?(interest) %>
                    <li class="match"><%= interest %></li>
                  <% else %>
                    <li><%= interest %></li>
                  <% end %>
                <% end %>
              </ul>
            <% end %>
          </div>

          <div class="small-3 columns">
            <h6 id="user-column-header"><%= project.user.username %></h6>
            <%= image_tag (project.user.profile_pic), size: "90x90" %>
          </div>
        </div>
      <% end %>
    </ul>
  <% end %>
  </div>
</body>

app/views/projects/show.html.erb
<nav class="top-bar">
  <ul class="title-area">
    <li class="name">
      <h1><a href="/" id="nav-bar-name">Endeavor</a></h1>
    </li>
  </ul>

  <section class="top-bar-section">
    <ul class="right">
      <%- if current_user -%>
        <li><%= link_to("Recommended Projects", recommended_projects_path) %></li>
        <li><%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></li>
        <li><%= link_to "My Profile",user_path(current_user) %></li>
      <%- else -%>
        <li><%= link_to 'Sign Up', new_user_registration_path %></li>
        <li><%= link_to 'Sign In', new_user_session_path %></li>
      <%- end -%>
    </ul>
  </section>
</nav>

<body class="project-page-body">
  <div class="row">
    <div class="small-10 small-centered columns">

      <div class="row">
        <div class="small-12 columns project-name">
          <h1><%= @project.name %></h1>
        </div>
      </div>

      <div class="row project-proposal-section">
        <div class="small-6 columns">
          <h3>Proposal</h3>
          <p class="proposal"><%= @project.proposal %></p>
        </div>

        <div class="small-6 columns">
          <% if current_user.id == @project.user.id %>
            <h3>You proposed this project</h3>
          <% else %>
            <h3>proposed by <%= @project.user.username %></h3>
          <% end %>
          <div class="project-profile-pic">
          <!-- <%= image_tag (@project.user.profile_pic), size: "140x140" %> -->
          <a href="/users/<%= @project.user.id %>"><%= image_tag (@project.user.profile_pic), size: "140x140" %></a>
          </div>
          <% unless current_user.id == @project.user.id %>
            <img src="<%= asset_path('contact-icon.png') %>">
            <%= mail_to(@project.user.email, "contact") %>
          <% end %>
        </div>
      </div>

      <div class="row">
        <div class="small-12 columns project-skills-section">
          <h3>Looking for those with skills in:</h3>
          <% if @skills.empty? %>
            <p><%= @project.name %> does not have any skills yet</p>
          <% else %>
            <ul>
              <% @skills.each do |skill| %>
                <li><%= skill.name %></li>
              <% end %>
            </ul>
          <% end %>
        </div>
      </div>

      <div class="row">
        <div class="small-12 columns project-interests-section">
          <h3>and interests in:</h3>
          <% if @interests.empty? %>
            <p><%= @project.name %> does not have any skills yet</p>
          <% else %>
            <ul>
              <% @interests.each do |interest| %>
                <li><%= interest.name %></li>
              <% end %>
            </ul>
          <% end %>
        </div>
      </div>

      <div class="row">
        <div class="small-12 columns recommended_users-section">
          <% if current_user.id == @project.user.id %>
            <% if @top_5_recommended_users.any? %>
              <h3>Top recommended users for your project</h3>
              <ul id="recommended-users-list">
                <% @top_5_recommended_users.each do |user| %>
                  <li><a href="/users/<%= user.id %>" data-dropdown="user-hover-<%= user.id %>" data-options="is_hover:true; hover_timeout:0"><%= user.username %></a>
                    <ul id="user-hover-<%= user.id %>" class="f-dropdown" data-dropdown-content>
                      <h6>Matches on:</h6>
                      <% matches(user, @project).each do |match| %>
                        <li><%= match.keys.first %>: <%= match.values.first %></li>
                      <% end %>
                    </ul>
                  </li>
                <% end %>
              </ul>
            <% else %>
              <h3>There are no recommended users for this project at this time</h3>
            <% end %>
          <% end %>
        </div>
      </div>

      <div class="row">
        <div class="small-12 columns project-actions">
          <% if @project.user_id == current_user.id %>
            <%= link_to("Edit My Project", edit_project_path(@project), class: "button small round edit-project") %>
          <% end %>

          <% if @project.user_id == current_user.id %>
            <%= link_to("Delete My Project", project_path(@project), method: :delete, class: "button small round delete-project") %>
          <% end %>
        </div>
      </div>

    </div>
  </div>
</body>

app/views/users/index.html.erb
<nav class="top-bar">
  <ul class="title-area">
    <li class="name">
      <h1><a href="/" id="nav-bar-name">Endeavor</a></h1>
    </li>
  </ul>

  <section class="top-bar-section">
    <ul class="right">
      <%- if current_user -%>
        <li><%= link_to("Recommended Projects", recommended_projects_path) %></li>
        <li><%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></li>
        <li><%= link_to "My Profile",user_path(current_user) %></li>
      <%- else -%>
        <li><%= link_to 'Sign Up', new_user_registration_path %></li>
        <li><%= link_to 'Sign In', new_user_session_path %></li>
      <%- end -%>
    </ul>
  </section>
</nav>

<body class="users-page">

<h1>All Users</h1>
<% unless @users.empty? %>
  <ul>
    <% @users.each do |user| %>
      <li><%= link_to(user.username, user_path(user)) %></li>
    <% end %>
  </ul>
<% end %>

</body>

app/views/users/show.html.erb
<nav class="top-bar">
  <ul class="title-area">
    <li class="name">
      <h1><a href="/" id="nav-bar-name">Endeavor</a></h1>
    </li>
  </ul>

  <section class="top-bar-section">
    <ul class="right">
      <%- if current_user -%>
        <li><%= link_to("Recommended Projects", recommended_projects_path) %></li>
        <li><%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></li>
        <li><%= link_to "My Profile",user_path(current_user) %></li>
      <%- else -%>
        <li><%= link_to 'Sign Up', new_user_registration_path %></li>
        <li><%= link_to 'Sign In', new_user_session_path %></li>
      <%- end -%>
    </ul>
  </section>
</nav>


<body class="user-page-body">
  <div class="row">
    <div class="small-12 columns profile-header">
      <%= image_tag (@user.profile_pic), size: "140x140" %>
      <% if @user.id == current_user.id %>
        <h1>My profile</h1>
      <% else %>
        <h1><%= @user.username %>'s profile</h1>
      <% end %>
    </div>
  </div>

  <div class="row">
    <div class="small-3 columns skills-section">
      <h3>Skills</h3>
      <% if @skills.empty? %>
        <p><%= @user.username %> has not listed any skills yet</p>
      <% else %>
        <ul>
          <% @skills.each do |skill| %>
            <li><%= skill.name %></li>
          <% end %>
        </ul>
      <% end %>
    </div>

    <div class="small-6 columns">
      <div class="row">
        <div class="small-12 columns about-me-section">
          <h6>About me: <%= @user.about_me %></h6>
        </div>
      </div>

      <div class="row">
        <div class="small-12 columns project-proposals-section">
          <h3>Projects proposed</h3>
          <% if @projects.empty? %>
            <p><%= @user.username %> has not created any projects yet</p>
          <% else %>
            <ul>
              <% @projects.each do |project| %>
                <li><%= link_to(project.name, project_path(project)) %></li>
              <% end %>
            </ul>
          <% end %>

          <% if @user.id == current_user.id %>
            <%= link_to("Propose a new project!", new_project_path, class: "button small round new-project") %>
          <% end %>
        </div>
      </div>

      <div class="row">
        <div class="small-12 columns recommended_projects-section">
          <% if @user.id == current_user.id %>
            <% if @top_5_recommended_projects.any? %>
              <h3>Top project recommendations</h3>
              <ul id="recommended-projects-list">
                <% @top_5_recommended_projects.each do |project| %>
                  <li><a href="/projects/<%= project.id %>" data-dropdown="project-hover-<%= project.id %>" data-options="is_hover:true; hover_timeout:0"><%= project.name %></a>
                    <ul id="project-hover-<%= project.id %>" class="f-dropdown" data-dropdown-content>
                      <h6>You match on:</h6>
                      <% matches(project, @user).each do |match| %>
                        <li><%= match.keys.first %>: <%= match.values.first %></li>
                      <% end %>
                    </ul>
                  </li>
                <% end %>
              </ul>
            <% else %>
              <h6>You have no recommended projects at this time</h6>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>

    <div class="small-3 columns interests-section">
      <h3>Interests</h3>
      <% if @interests.empty? %>
        <p><%= @user.username %> has not listed any interests yet</p>
      <% else %>
        <ul>
          <% @interests.each do |interest| %>
            <li><%= interest.name %></li>
          <% end %>
        </ul>
      <% end %>
    </div>

    <% unless @user.id == current_user.id %>
      <div class="row">
        <div class="small-12 columns contact">
          <img src="<%= asset_path('contact-icon.png') %>">
          <%= mail_to(@user.email, "contact #{@user.username}") %>
        </div>
      </div>
    <% end %>

    <% if @user.id == current_user.id %>
      <div class="row">
        <div class="small-12 columns profile-actions">
            <%= link_to("Edit My Profile", edit_user_registration_path, class: "button small round edit-profile") %>
            <%= link_to("Delete My Profile", project_path(@user), method: :delete, class: "button small round delete-profile") %>
        </div>
      </div>
    <% end %>
  </div>
</body>